ALPHA_VANTAGE_API_KEY = 'your_alpha_vantage_api_key'
NEWS_API_KEY = 'your_news_api_key'
TWILIO_ACCOUNT_SID = 'your_twilio_account_sid'
TWILIO_AUTH_TOKEN = 'your_twilio_auth_token'
TWILIO_PHONE_NUMBER = 'your_twilio_phone_number'
TO_PHONE_NUMBER = 'your_phone_number'
COMPANY_NAME = 'your_company_name'
STOCK_NAME = 'your_stock_name'
